### PR TITLE
Ordering bindable members

### PR DESCRIPTION
**Pull request by nakhbari**
* We order the bindable members at the top 
  * The member variables should come before the member functions
  * Within the member variables/function should be ordered alphabetically
```javascript
  function FooController() {
    var vm = this;

    vm.error = undefined;
    vm.foo = 'foo';
    vm.bar = Bar;
    vm.num = Num;

    function Bar() {
      /* code block */
      vm.error = "error";
    }

    function Num() {
      /* code block */
    }
  }
```

### CODE REVIEW

**Comment by mpiggott** [comment]
I prefer alphabetical, though as per #5 I disagree with this style in general

**Comment by mpiggott** [comment]
Similar to the comment in #9 in Java we don't proscribe ordering so I'm not sure why we would here

**Comment by dbradicich** [comment]
As i consider this more (I was initially on a +1 boat) I'm thinking it doesn't really matter and alphabetical should be ok, reason being is that we aren't actually putting the function code in this ordering, its really just a list of variables which we later assign value or functions to...

So if i'm the one that initially had this idea (or helped push it along), sorry!  ;)

-1

**Comment by whyjustin** [comment]
+0

**Comment by bmurmistro** [comment]
+1 on the vars before functions, but the ordering I'm +0

**Comment by seminolas** [comment]
+0. if I have so many variables that it's getting hard to find what I need, I'll make some effort to fix that. that may be ordering as proposed in here, or some grouping by function or whatever else feels right in the context. if the number of variables is small, it doesn't really matter anyway.

**Comment by nakhbari** [comment]
As per our discussion [1], this proposed style is declined. It's up to the developer to decide the order.

[1]https://docs.google.com/spreadsheets/d/1eFKyXJsOPDrqxppQQXzwGpuG8CZV33h9OYu2M5GTPv0/edit#gid=0

**Pull request closed without merging**
