### PR TITLE
Order attributes according to following priorities

### PR DESCRIPTION
**Pull request by nakhbari**
#### HTML
* Attributes should be ordered according to the following priorities
  * ```id``` > ```class``` > others
```html
  <textarea id="foo" class="bar" name="name" rows="2" ng-model="baz" ng-maxlength="255"></textarea> 
```

### CODE REVIEW

**Comment by mpiggott** [comment]
I don't think this needs to be specified.

**Comment by dbradicich** [comment]
> I don't think this needs to be specified.

I'm not against it, go ahead and state it, and maybe I'll start adhering to it (I know i'm guilty of sticking attributes in willy-nilly)

+1

**Comment by mpiggott** [comment]
I guess I would point out that we don't proscribe the order of attributes or methods in Java.

**Comment by bentmann** [comment]
> I guess I would point out that we don't proscribe the order of attributes or methods in Java.

Correct, the thinking is that IDEs allow to navigate/search class members effeciently independently of their declared order in the code such that we don't need to worry about it and can focus our energy elsewhere than to shuffle code around.

I don't work with HTML often but I feel with Matthew that this order convention seems overly restrictive and a burden on developers to adhere here to and maintain.

**Comment by whyjustin** [comment]
> the thinking is that IDEs allow to navigate/search class members efficiently independently of their declared order in the code

I think the difference with HTML is that the id of an element is similar to the class/member name with the type being declared first. In the example above I see
```
<textarea id='foo' ....
```
as being equivalent to
```
public textarea foo;
```
Beyond the id, I'm somewhat ambivalent of the order and believe an absolute prescription teeters on violating out tenant that "The guidelines are short and written with consideration that different developers approach problems differently".

**Comment by dbradicich** [comment]
I definitely prefer ```id``` attribute first, regardless of IDE search-ability, it's much simpler on visual scanning, and as justin said, other attributes are kinda...whatever ;)

**Comment by bmurmistro** [comment]
+0 I'm on board with id being first, but I don't think the ordering of others buys us much.

**Comment by whyjustin** [comment]
Just to expand on the above a bit, I do understand @nakhbari concern about class coming from the fact that class name selectors are available in CSS which makes the class value a certain type of ID. In the view of CSS it is possible to think of
```
<textarea class='foo' ...
```
as being equivalent to
```
public textarea '.foo'
```

**Comment by seminolas** [comment]
+0. id being first makes sense. the most 'natural' layout for other attributes will vary.

**Pull request closed without merging**
