### PR TITLE
Align IDEA and Eclipse javascript codestyle flags for newline after [ and before ]

### PR DESCRIPTION
**Pull request by dbradicich**
I opted to just change the IDEA side to match eclipse

```
var promises = [
  TagStore[vm.loadError ? 'refresh' : 'get'](), TagStore.getApplied(), ApplicationStore.get(),
  PolicyHierarchyStore.get(), PolicyTagStore.getApplied()
], policyMap = {};
```

is now

```
var promises = [TagStore[vm.loadError ? 'refresh' : 'get'](), TagStore.getApplied(), ApplicationStore.get(),
                PolicyHierarchyStore.get(), PolicyTagStore.getApplied()], policyMap = {};
```

Initially discussed here https://github.com/sonatype/insight-brain/pull/1804#discussion_r54445171

### CODE REVIEW

**Comment by mpiggott** [comment]
Should the second variable also be on its own line?

**Comment by dbradicich** [comment]
> Should the second variable also be on its own line?

doesn't appear to be something i can set in the IDEA code formatting..

**Comment by mpiggott** [comment]
+1

**Comment by dbradicich** [comment]
This obviously hasn't been an issue as the PR now sits here 2+ years later, so closing

**Pull request closed without merging**
