### PR TITLE
Increase line length to 160 characters

### PR DESCRIPTION
**Pull request by ajdranse**

### CODE REVIEW

**Comment by vladt** [comment]
-1 I find 120 too long in many cases. It's simply hard to read very long lines. 160 is obviously worse, in my opinion.

**Comment by SirMaster** [comment]
👍

**Comment by regoarrarr** [comment]
I am also -1. Can someone share some examples of code that needs to be longer than 120 characters that wouldn't be at least as well off if not better broken out into smaller, more readable chunks?

**Comment by bradcupit** [comment]
@regoarrarr I'm not suggesting all lines should be 160, but sometimes the line is mostly boilerplate and wrapping the line makes it harder to read. In those cases it would be nice to have more flexibility in the length. Here's an example from the [email discussion](https://groups.google.com/a/sonatype.com/d/msg/dev/AWFGravjn4k/PyoB5huuBwAJ):

image

**Comment by Blacktiger** [comment]
> @regoarrarr I'm not suggesting all lines should be 160, but sometimes the line is mostly boilerplate and wrapping the line makes it harder to read. In those cases it would be nice to have more flexibility in the length. Here's an example from the [email discussion](https://groups.google.com/a/sonatype.com/d/msg/dev/AWFGravjn4k/PyoB5huuBwAJ):
> 
> image

Why not just break up the arguments completely like this?

```
ClusterRow(
  1,
  REPOSiTORY_NPM,
  "PackageP",
  "1.9",
  "PackageHashP19",
  "ContentHash4",
  "ContentHash4",
  "",
  "",
  "FileF.js",
  new Timestamp(19)
)
...
```

IMO code like the example isn't good anyway - it's too easy to mix up the multiple String arguments not to mention difficult to understand which argument is for what purpose. IntelliJ will try to help you understand by naming the arguments, but that only makes the line even _longer_ and harder to read. That feels like a good place to consider using a builder to me.

**Comment by sbaker617** [comment]
> Why not just break up the arguments completely like this?

that turns 5 lines @160 into 65 lines... comparing all of the contents of items 2 & 5 (for example) would be significantly more difficult.  I like builders in general, but for the example they'd have a similar impact & just add in a bunch of setSomeThingOrOther() calls.

a longer line length allows for greater information density in places where that's desired/useful.  setting up test objects like in the example is one place that helps to simplify development.

**Review by paulerickson — APPROVED** [review]

**Comment by rpokorny** [comment]
-1.  I commonly have two files open side-by-side.  120 is already a hair too long for that to work without wrapping.  160 would put it out of the question.

**Comment by regoarrarr** [comment]
@ajdranse This PR is 2 years old. Since it does not seem like there is consensus, can we close it (or seek to find consensus)?

**Comment by bradcupit** [comment]
we're keeping it open until @vladt, @regoarrarr, and @rpokorny retire, then we'll merge 👍 

just kidding 😛 
Wes did a poll back when this was live, and it was well under having a consensus, so yes, we should close it.

**Comment by ajdranse** [comment]
I totally thought I already closed it.  Fixing that mistake now.

**Pull request closed without merging**
