### PR TITLE
Changed the Eclipse java formatter for method and constructor parameters to match the formatting used by the Nexus team

### PR DESCRIPTION
**Pull request by vladt**
Changes voted in the "Java method parameter formatting" email thread on Dec 4th, 2015. There were 5 votes for the Nexus style and 1.5 votes for the CLM style.

### CODE REVIEW

**Comment by bentmann** [comment]
+1, as long as it matches IntelliJ

**Comment by vladt** [comment]
> as long as it matches IntelliJ

For Intellij, I hope a developer that uses it will step up and make the corresponding changes.

**Comment by whyjustin** [comment]
> For Intellij, I hope a developer that uses it will step up and make the corresponding changes.

IntelliJ does this by default. FWIW the setting for CSS seems to be the only place where we don't [0] follow this pattern although I don't think I've ever seen the results of this.

https://github.com/sonatype/codestyle/blob/9f8ee565e42bed38b8515ff97832e5e98804bf4d/sonatype-idea.xml#L91

**Comment by whyjustin** [comment]
+1

**Comment by bhamail** [comment]
+1. BTW, I'm pretty sure we had changed the default for IDEA in this area. I'll take a look and update it if needed.

**Comment by vladt** [comment]
Merged to master

**Pull request closed without merging**
