### PR TITLE
Support Jenkins builds

### PR DESCRIPTION
**Pull request by tneer**
https://jenkins.zion.aws.s/job/tools/job/codestyle/job/feature-snapshots/job/jenkins/lastBuild/

Updates the project settings and adds Jenkins support so that the PMD and Checkstyle rules can be built by CI and made available for inclusion in maven projects.

This project is set up to provide it's own pipeline library for providing make and notification functionality.

### CODE REVIEW

**Comment by rpokorny** [comment]
The files in the `vars` directory mostly duplicate files that we have elsewhere.  Is there a way to implement those somewhere reusable?

**Comment by tneer** [comment]
> The files in the vars directory mostly duplicate files that we have elsewhere. Is there a way to implement those somewhere reusable?

There may be, but I'm not sure I like it.  So for I've been treating the Jenkins shared libraries as if they are in a hierarchy:

private-pipeline-library
  jenkins-shared
    project/group level

In that hierarchy, the children can reference parents, but not the children.  

This is not required by Jenkins or Groovy, I was just trying to have some sort of logical grouping to make it easier to understand what is being invoked and where it is defined.

Right now, make.groovy is at the project/group level.  And, yes, this make.groovy is an exact copy at this point of the iq-pipeline-library version.  buildNotifications.groovy has a fair amount of overlap.  

So, I could move make.groovy to the middle layer, but then it would depend on a child providing an implementation of buildNotifications.groovy   I might be able to add some smarts and have a default version.  Haven't tried to see if this would work.

Alternately, I could move make.groovy and buildNotifications.groovy to the middle layer and add some call-backs/extension points for providing project/group level custom notifications.  This might be a little cleaner, but I'm not sure if the other teams will want to use similar notification mechanisms or not. 

In any case, all of that seemed like a lot of work not directly related to the task at hand.

**Comment by rpokorny** [comment]
> Right now, make.groovy is at the project/group level. And, yes, this make.groovy is an exact copy at this point of the iq-pipeline-library version. buildNotifications.groovy has a fair amount of overlap.

How much variance is there in different `buildNotifications.groovy` scripts?  I just checked this one against the iq one and the only difference is triggering a HC notification.  If that's the only difference across various projects I'd just make the HC room name a parameter in order to make it reusable.

**Comment by tneer** [comment]
>  I just checked this one against the iq one and the only difference is triggering a HC notification. If that's the only difference across various projects I'd just make the HC room name a parameter in order to make it reusable.

I really don't know how other teams want to do notifications?  @bigspotteddog  @wwannemacher , what are your thoughts on this?

**Comment by wwannemacher** [comment]
> I really don't know how other teams want to do notifications. @bigspotteddog @wwannemacher , what are your thoughts on this?

I abstracted the nxrm stuff into notifyChat.groovy. I wanted two things: 1. to get reasonably close to the hipchat notifications that bamboo is currently sending, and 2. to have an abstraction so that the move to slack can be a bit easier (when it happens).

**Pull request merged**
