### PR TITLE
Denote future bindable members

### PR DESCRIPTION
**Pull request by nakhbari**
* We denote future bindable members at the top of Angular controllers
```javascript
  function FooController() {
    var vm = this;

    vm.error = undefined;
    vm.bar = Bar;
    vm.foo = 'foo';

    function Bar() {
      /* code block */
      vm.error = "error";
    }
  }
```

### CODE REVIEW

**Comment by mpiggott** [comment]
On interesting quirk with `error` in particular, the state after the error is actually different than the initial state as we're commonly using `delete`

**Comment by dbradicich** [comment]
> On interesting quirk with error in particular, the state after the error is actually different than the initial state as we're commonly using delete

is it really?  I was doing some testing and undefined seemed to be the value on initial assignment and after delete

**Comment by dbradicich** [comment]
+1

**Comment by whyjustin** [comment]
+1

**Comment by bmurmistro** [comment]
+1

**Comment by mpiggott** [comment]
> is it really? I was doing some testing and undefined seemed to be the value on initial assignment and after delete

This sets a property with the value `undefined` after we use delete the object no longer has the property.

**Comment by seminolas** [comment]
+1

**Pull request closed without merging**
